### ISSUE TITLE
Compile on FreeBSD

### ISSUE THREAD

**Issue by FreeBSD-pzn** [JonathanBelanger/DECaxp#3]
Hi Jonathan!
Thank you to answered me!

I have attentively read all COPYRIGHTS, RULES and NOTES of DECaxp.
And I will honor them!

Well, I am using FreeBSD(10.4-stable, 11.1-release,11.2-release and 11.1-stable),
also I have got MacOS(Darwin) and Solaris 10.

To compile DECaxp under FreeBSD I need a little change of source code.
I did not change the base code of DECaxp. I only change lines in which has been
#include directives and I do convert DOS to UNIX style.

For example:
in the file >>  ../cpu/AXP_21264_Ebox_PALfunctions.c
----------------------------------------------------
has been    >> #include "AXP_21264_Ebox_PALFunctions.h"

has become  >> #include "AXP_21264_Ebox_PALfunctions.h"

Also I can upload all changed files to inspect them.

Oleg
p.s.
I know that my English is "a very poor", I study it.
And sorry for my English and forgive me, if I made a mistake in the text.

**Comment by JonathanBelanger** [comment]
Your English is fine (mine is terrible 8-)

If you can tell me where there are any file case problems, please let me now and I'll fix them in the code.

Thanks.

**Comment by sskras** [comment]
@FreeBSD-pzn , can you generate a diff file and insert here?  if you wrap it with three backticks (```) before the starting line and after the final line, it becomes a fixed font.

Or make a pull request (which I haven't learned yet, so no advises).

**Comment by JonathanBelanger** [comment]
If you go over to @freeBSD-pzn clone of this project and look at the differences there, you can see what he did.
