### ISSUE TITLE
License of the DECaxp

### ISSUE THREAD

**Issue by sskras** [JonathanBelanger/DECaxp#5]
Hi @JonathanBelanger .  In the commit 6198fcef13d2ec034b2f96468315ca1cdbe00f8e (one of the first) I read:

```
/*
 * Copyright (C) Jonathan D. Belanger 2017.
 * All Rights Reserved.
 *
 * This software is furnished under a license and may be used and copied only
 * in accordance with the terms of such license and with the inclusion of the
 * above copyright notice.  This software or any other copies thereof may not
```

Does this text mean some specific, particular software license name?  

This project sounds too awesome.  So I tried identifying its license.  By googling the first line I found an example from an [old book by DEC](https://books.google.lt/books?id=0EWjBQAAQBAJ&pg=PA97&lpg=PA97&dq=%22This+software+is+furnished+under+a+license+and+may+be+used+and+copied+only%22&source=bl&ots=OdSzIPv21O&sig=48bDIEgr86emKetCBgKv_XgaQ5g&hl=en&sa=X&ved=2ahUKEwi3sN_srO_eAhWJ1iwKHXPMDvgQ6AEwAnoECAcQAQ#v=onepage&q=%22This%20software%20is%20furnished%20under%20a%20license%20and%20may%20be%20used%20and%20copied%20only%22&f=false) which contains the same phrasing.  But no license name.

Then I found the similar phrasing in the license of enhancements to OpenMotif-2.2.2:
http://ftp.lanet.lv/ftp/mirror/Slackware/extra/openmotif-2.2.2/LICENSE

... which here is called **The Open Group Public License** .  Though the pointed full details of it has no phrase like "This software is furnished under a license" already:
http://www.opengroup.org/openmotif/license/

So again I am not sure about the name of a license `DECaxp` uses.

**Comment by sskras** [comment]
More from the header:

```
 * above copyright notice.  This software or any other copies thereof may not
 * be provided or otherwise made available to any other person.  No title to
 * and ownership of the software is hereby transferred.
 *
 * The information in this software is subject to change without notice and
 * should not be construed as a commitment by the author or co-authors.
```

This ("may not be provided") doesn't sound like an open source project.  Do I get this right?

PS. Once again, the project is great.  I was introduced into OpenVMS and AlphaServer models GS80+GS1280 last year.  And I started thinking about rewriting `es40` in plain C.  Today I found `DECaxp` and I think I would like to join it.  But first the license question : )

Thanks.

**Comment by JonathanBelanger** [comment]
This is not an entirely open source project.  I do not have problems with people cloning it, but I don't want anyone to sell it or use it in any commercial way.  I don't know what the future for this work is, but I am seriously considering making it truly open source.

**Comment by JonathanBelanger** [comment]
Sorry, I didn't mean to close this, so that we can keep the dialog open.

**Comment by JonathanBelanger** [comment]
DECaxp is going to be open source for non-commercial use.  If at any point in the future, a commercial entity wished to use this software, they will be licensing costs.  When this happens, this open source GitHub repository will have to be converted.  The licensing costs will be used to offset those costs.  Please let me know if you have any issues with this.

Thanks.

**Comment by JonathanBelanger** [comment]
I made it a GPL 3.0 license.  I will be closing this now.

**Comment by sskras** [comment]
(Ah, missed that one in the stream of other notifications)
Thanks. So you chose to use GPL-3.0 : )

A month ago I was about to offer a [BlueOak-1.0.0](https://blueoakcouncil.org/2019/03/06/model.html), a recently introduced, simple and legally complete _permissive_ license which maintains patent safety too (like Apache-2.0). But I guess BlueOak it's too permissive for your aims.  

OTOH, I am not sure whether GPL-3.0 will need to be changed at all for `DECaxp` when going commercial:
https://www.gnu.org/licenses/gpl-faq.en.html#GPLCommercially
> **If I use a piece of software that has been obtained under the GNU GPL, am I allowed to modify the original code into a new program, then distribute and sell that new program commercially?** (#GPLCommercially)
> 
> You are allowed to sell copies of the modified program commercially, but only under the terms of the GNU GPL. Thus, for instance, you must make the source code available to the users of the program as described in the GPL, and they must be allowed to redistribute and modify it as described in the GPL.
> 
> These requirements are the condition for including the GPL-covered code you received in a program of your own.

So you just add another, proprietary license text here and are all set, I think. Commercial users of the code would choose proprietary way, and FLOSS contributors like me would go with GPL-3.0.

Does this sound right?

**Comment by JonathanBelanger** [comment]
Sounds reasonable.  I was actually using the descriptions of when to use which license, and this one seemed more in-line with my aims.  Also, with the changes to patent laws, which no longer are based on when a patent was submitted, but when the patent-able idea was discovered, and by whom, then if I were ever going to patent any ideas I have created through this project, then I'm still covered.  Also, my only requirement is that if someone works on this project and comes up with a patent-able idea that they then patent, then the patent is theirs, but any use of that patent within this code is automatically licensed at no cost within this code.  I don't see other peoples patents transferring to other projects or royalties coming to me.  It is the right thing to do.
