### ISSUE TITLE
signal.h error

### ISSUE THREAD

**Issue by TheFausap** [JonathanBelanger/DECaxp#7]
Hello Jonathan,
in the file /home/fausap/DECaxp/Devices/DS12887A_TOYClock/AXP_DS12887A_TOYClock.c there's the include of `cygwin/signal.h`, but the include assumes cygwin, so there should be a check if we are under CYGWIN or not.
Under linux signal.h is included without any subdirectory.

**Comment by JonathanBelanger** [comment]
Good catch.  I'll fix this in my next cycle.  I'm in the middle redesigning all the caches (iCache, dCache, and bCache).

**Comment by JonathanBelanger** [comment]
I fixed this one and checked that there were no others like it.  It should be good to go.
