### ISSUE TITLE
CPU Initialization Load File.dat missing

### ISSUE THREAD

**Issue by TheFausap** [JonathanBelanger/DECaxp#8]
Hello Jonathan,

I was trying to run DECaxp under cygwin64, but I noticed one of the initialization files is missing, that one in the subject.
Do I have to generate it in some way?

thanks,
Fausto

**Comment by JonathanBelanger** [comment]
I apparently have a segfault in there as well.  Chasing it down now.

**Comment by JonathanBelanger** [comment]
I found quite a few small bugs.  One in particular, never worked, and should have generated a segfault.  If reallocating a block, the old block would get copied into the wrong place, and not it's entire length.  I also updated the configuration file, but the `CPU Initialization Load File.dat' is still missing, but there is no place where it is loaded (any more), but there will be at some point.  Also, the XML parsing code had a bunch of problems, potentially writing to memory it should not.  It all compiles, but the system code is all missing, so this is where it will segfault. 

Submit another issue, if you find any more.
